### PR TITLE
Fix selected module with args

### PR DESCRIPTION
**Pull request by jboss38**
See: https://github.com/AlessandroZ/LaZagne/issues/101

Tested.

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Hi, 

I cannot merge your pull request because I need to allow the function to run "all" module if not arguments are passed. However, the correction could be done elsewhere. The category is already retrieved in the "category_choosed" variable (https://github.com/jboss38/LaZagne/blob/ea78ba8d0a772b90de027190ee6b1b638f990bfe/Windows/laZagne.py#L364). 

Then the main function is called here: https://github.com/jboss38/LaZagne/blob/ea78ba8d0a772b90de027190ee6b1b638f990bfe/Windows/laZagne.py#L373

So you change the line "for r in runLaZagne():" by "for r in runLaZagne(category_choosed):" and restore the line you have changed "def runLaZagne(category_choosed='all'):" 

It should work like that. If you can test it and change your pull request and I will commit it. 

Thanks again !

**Comment by jboss38** [comment]
Oh yea my bad.

I just tested, it's working fine.

**Comment by jboss38** [comment]
I cannot cancel the first commit, can you ?

**Comment by AlessandroZ** [comment]
Good job, thanks for your work. 
Don't worry, the last commit will modify every previous commit.

**Pull request merged**
