### PR TITLE
Travis CI: Add a parallel build on os: windows

### PR DESCRIPTION
**Pull request by cclauss**
As discussed at #380

### CODE REVIEW

**Comment by AlessandroZ** [comment]
This PR does not pass some tests: https://travis-ci.com/AlessandroZ/LaZagne/jobs/188865951#L353

I think the windows system does not have `C:\\Windows\\System32\\msvcp100.dll` because it's too recent (`Windows-10-10.0.17134`). I think `msvcp120` should be there but I don't know if running the exe on old version would be possible.

**Comment by cclauss** [comment]
Agreed.  The PR is a _work in progress_ until the tests pass (or I give up)...

$ __ls -l /c/Windows/System32/msvcp*.dll__
```
-rwxr-xr-x 2 travis 197121 589912 Apr 11  2018 /c/Windows/System32/msvcp110_win.dll
-rwxr-xr-x 1 travis 197121 660128 Oct  4  2013 /c/Windows/System32/msvcp120.dll
-rwxr-xr-x 3 travis 197121 690008 Apr 11  2018 /c/Windows/System32/msvcp120_clr0400.dll
-rwxr-xr-x 1 travis 197121 627440 Oct 13 20:51 /c/Windows/System32/msvcp140.dll
-rwxr-xr-x 1 travis 197121  30960 Oct 13 20:50 /c/Windows/System32/msvcp140_1.dll
-rwxr-xr-x 1 travis 197121  37616 Oct 13 20:51 /c/Windows/System32/msvcp140_1d.dll
-rwxr-xr-x 1 travis 197121 205552 Oct 13 20:51 /c/Windows/System32/msvcp140_2.dll
-rwxr-xr-x 1 travis 197121 396016 Oct 13 20:51 /c/Windows/System32/msvcp140_2d.dll
-rwxr-xr-x 1 travis 197121 981744 Oct 13 20:50 /c/Windows/System32/msvcp140d.dll
-rwxr-xr-x 2 travis 197121 613376 Apr 11  2018 /c/Windows/System32/msvcp60.dll
-rwxr-xr-x 2 travis 197121 642088 Sep 11  2018 /c/Windows/System32/msvcp_win.dll
```

**Comment by cclauss** [comment]
Magic...  https://chocolatey.org/packages/vcredist-all/1.0.0 installed __C:\\Windows\\System32\\msvcp100.dll__

**Comment by cclauss** [comment]
Arrgghh... $ __dist/lazagne.exe all__
```
The command "dist/lazagne.exe all" exited with 126.
```

**Comment by cclauss** [comment]
Closing...  Wine is fine.

**Pull request closed without merging**
