### PR TITLE
Improve KeePass recovery, fix AES, PEP8

### PR DESCRIPTION
**Pull request by ingested**
PyAes only allows to encypt/decrypt data of length 16, so data must be processed in chunks with paddings. You should consider that when removing Pycrypto

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Thanks for the PR 👍 
For pyAes right now I don't see a real problem because block size was already 16 bytes so it should work well. But if you think I'm wrong, give me an example of module and I will try to find a solution. 
I had too much problems with pycrypto that I decided to remove it. It's a very good library but it's very big and when I did some tests with old systems, it was very complicated to install. On linux, sometimes I never suceed to install it.

**Comment by prepare2die** [comment]
No, PyAes is good, I just mean you should do something like this https://github.com/AlessandroZ/LaZagne/blob/646cd2e57ac09188fbbdc85333b37995b93ed358/Windows/lazagne/softwares/memory/libkeepass/crypto.py#L21 instead of https://github.com/AlessandroZ/LaZagne/blob/a214f9d1115b444c0d7a2bb78e01394a38bbff7f/Windows/lazagne/softwares/memory/libkeepass/crypto.py#L21

Same thing for decryption

**Comment by ingested** [comment]
No, PyAes is good, you should do something like this https://github.com/AlessandroZ/LaZagne/blob/646cd2e57ac09188fbbdc85333b37995b93ed358/Windows/lazagne/softwares/memory/libkeepass/crypto.py#L21 instead of https://github.com/AlessandroZ/LaZagne/blob/a214f9d1115b444c0d7a2bb78e01394a38bbff7f/Windows/lazagne/softwares/memory/libkeepass/crypto.py#L21

Same thing for decryption

**Comment by AlessandroZ** [comment]
Hi @ingested, 

I was working on upgrading to Python 3 (but I want to keep the Python 2 compatibility as well). However, it's super long and needs lot of time (and tests). However, right now, I have spend too much time on it (I didn't except so much work). I have managed to run the tool (which it was not easy at first with all problem dependencies that change names). But righ now, I have lots of encoding problem (because .decode() does not exists on Python 3). I don't want to break all the work I did on Python 2 to manage unicode using decode, so I don't want to change everything. 
If you have some time to take a look, your help will be much than appreciate. 
I have removed some decode function [here](https://github.com/AlessandroZ/LaZagne/commit/68ae06d16eecccab53631aa3391f9170faab9fd9) and I hope nothing has been broken. Browsers modules should work on python 2 and python 3. 
Moreover, "split" cannot be run on bytes on python 3, so on [wifi](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py#L38) module, I have an error. It work doing decode('latin') but an error occured decoding using 'utf-8'. So I think for non latin OS, it should not work. 

If you have some time to take a look on these encoding problem, it would be awesome. Thanks a lot.

**Comment by ingested** [comment]
Hi @AlessandroZ 

I didn't have much time recently, but I'll definitely take a look. Glad you were able to run it on python3, nice work 👏

**Pull request merged**
