### PR TITLE
Add new extractors

### PR DESCRIPTION
**Pull request by righettod**
Hello,

I have added 3 extractors in order to extract:

1) The repositories's credentials used by Maven java build tool:
3 cases are handled:
* Authentication using password protected with the master password (encrypted)
* Authentication using password not protected with the master password (plain text)
* Authentication using private key

2) The connections credentials for "Apache Directory Studio" (ldap browser) application.

3) The unprotected private keys for "OpenSSH" application.

Thanks in advance  :+1:

### CODE REVIEW

**Comment by righettod** [comment]
Hi,

Wait a last commit before to integrate the PR because I need to fix a error in command shortcut.

Sorry.

**Comment by righettod** [comment]
Command shortcuts has been fixed.
You can integrate the PR if you are agree with my proposal.
Thanks in advance.

**Comment by AlessandroZ** [comment]
Thank you for your commits, I will create the binary today. Nice job !

**Comment by righettod** [comment]
Hi

Thanks you very much for the merge.

This product is amazing :)

**Comment by AlessandroZ** [comment]
The binary has been created: https://github.com/AlessandroZ/LaZagne/releases/tag/1.5

Thanks again for your contribution, this is the reason I wanted to put it as an open source project. 
:)

**Comment by righettod** [comment]
Thanks you very much :)

**Pull request merged**
