### PR TITLE
Fix 459

### LINKED ISSUE #459: latest laZagne.py doesn't run
Hello:
raw cmd ;
C:\Windows\system32>cd C:\Users\TESTACCOUNT\Desktop\Python37

C:\Users\TESTACCOUNT\Desktop\Python37>pip install -r "C:\lago\requirements.txt"
Ignoring enum34: markers 'python_version < "3.4" and sys_platform == "win32"' don't match your environment
Ignoring psutil: markers 'sys_platform == "linux" or sys_platform == "linux2"' don't match your environment
Ignoring secretstorage: markers 'sys_platform == "linux" or sys_platform == "linux2"' don't match your environment
Collecting https://github.com/AlessandroZ/pypykatz/archive/master.zip (from -r C:\lago\requirements.txt (line 6))
  Downloading https://github.com/AlessandroZ/pypykatz/archive/master.zip
     / 1.2MB 1.3MB/s
Requirement already satisfied (use --upgrade to upgrade): pypykatz==0.0.3 from https://github.com/AlessandroZ/pypykatz/archive/master.zip in c:\users\testaccount\desktop\python37\lib\site-packages (from -r C:\lago\requirements.txt (line 6))
Requirement already satisfied: pyasn1 in c:\users\testaccount\desktop\python37\lib\site-packages (from -r C:\lago\requirements.txt (line 3)) (0.4.8)
Requirement already satisfied: rsa in c:\users\testaccount\desktop\python37\lib\site-packages (from -r C:\lago\requirements.txt (line 4)) (4.0)

C:\Users\TESTACCOUNT\Desktop\Python37>pip install --upgrade pypykatz
Collecting pypykatz
  Using cached https://files.pythonhosted.org/packages/68/4a/2436e462a7c9ad3df263f5b14998b664bdc62f2d4352af142b5defafeada/pypykatz-0.3.2-py3-none-any.whl
Requirement already satisfied, skipping upgrade: minidump>=0.0.11 in c:\users\testaccount\desktop\python37\lib\site-packages (from pypykatz) (0.0.11)
Requirement already satisfied, skipping upgrade: minikerberos>=0.0.11 in c:\users\testaccount\desktop\python37\lib\site-packages (from pypykatz) (0.0.11)
Requirement already satisfied, skipping upgrade: msldap>=0.1.1 in c:\users\testaccount\desktop\python37\lib\site-packages (from pypykatz) (0.2.5)
Requirement already satisfied, skipping upgrade: aiowinreg>=0.0.1 in c:\users\testaccount\desktop\python37\lib\site-packages (from pypykatz) (0.0.2)
Requirement already satisfied, skipping upgrade: winsspi>=0.0.3 in c:\users\testaccount\desktop\python37\lib\site-packages (from pypykatz) (0.0.3)
Requirement already satisfied, skipping upgrade: asn1crypto in c:\users\testaccount\desktop\python37\lib\site-packages (from minikerberos>=0.0.11->pypykatz) (1.2.0)
Requirement already satisfied, skipping upgrade: ldap3<2.5.2 in c:\users\testaccount\desktop\python37\lib\site-packages (from msldap>=0.1.1->pypykatz) (2.5.1)
Requirement already satisfied, skipping upgrade: asciitree in c:\users\testaccount\desktop\python37\lib\site-packages (from msldap>=0.1.1->pypykatz) (0.3.3)
Requirement already satisfied, skipping upgrade: socks5line>=0.0.3 in c:\users\testaccount\desktop\python37\lib\site-packages (from msldap>=0.1.1->pypykatz) (0.0.3)
Requirement already satisfied, skipping upgrade: aiocmd in c:\users\testaccount\desktop\python37\lib\site-packages (from msldap>=0.1.1->pypykatz) (0.1.2)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.8 in c:\users\testaccount\desktop\python37\lib\site-packages (from ldap3<2.5.2->msldap>=0.1.1->pypykatz) (0.4.8)
Requirement already satisfied, skipping upgrade: prompt-toolkit>=2.0.9 in c:\users\testaccount\desktop\python37\lib\site-packages (from aiocmd->msldap>=0.1.1->pypykatz) (3.0.2)
Requirement already satisfied, skipping upgrade: wcwidth in c:\users\testaccount\desktop\python37\lib\site-packages (from prompt-toolkit>=2.0.9->aiocmd->msldap>=0.1.1->pypykatz) (0.1.7)
Installing collected packages: pypykatz
  Found existing installation: pypykatz 0.0.3
    Uninstalling pypykatz-0.0.3:
      Successfully uninstalled pypykatz-0.0.3
Successfully installed pypykatz-0.3.2

C:\Users\TESTACCOUNT\Desktop\Python37>python C:\lago\Windows\laZagne.py"
usage: laZagne.py [-h] [-version]
                  {all,browsers,chats,databases,games,git,mails,maven,memory,multimedia,php,svn,sysadmin,windows,wifi}
                  ...

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

positional arguments:
  {all,browsers,chats,databases,games,git,mails,maven,memory,multimedia,php,svn,sysadmin,windows,wifi}
                        Choose a main command
    all                 Run all modules
    browsers            Run browsers module
    chats               Run chats module
    databases           Run databases module
    games               Run games module
    git                 Run git module
    mails               Run mails module
    maven               Run maven module
    memory              Run memory module
    multimedia          Run multimedia module
    php                 Run php module
    svn                 Run svn module
    sysadmin            Run sysadmin module
    windows             Run windows module
    wifi                Run wifi module

optional arguments:
  -h, --help            show this help message and exit
  -version              laZagne version

C:\Users\TESTACCOUNT\Desktop\Python37>"C:\lago\Windows\laZagne.py" -version
Version 2.4.3

C:\Users\TESTACCOUNT\Desktop\Python37>"C:\lago\Windows\laZagne.py" all -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[!] Python 3.7.6 on Windows AMD64: Intel64 Family 6 Model 30 Stepping 5, GenuineIntel

Traceback (most recent call last):
  File "C:\lago\Windows\laZagne.py", line 233, in <module>
    for r in runLaZagne(category_selected=category, subcategories=subcategories, password=args.get('password', None)):
  File "C:\lago\Windows\laZagne.py", line 87, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories, password=password):
  File "C:\lago\Windows\lazagne\config\run.py", line 169, in run_lazagne
    constant.system_dpapi = SystemDpapi()
  File "C:\lago\Windows\lazagne\config\dpapi_structure.py", line 164, in __init__
    LSASecrets().run()
  File "C:\lago\Windows\lazagne\softwares\windows\lsa_secrets.py", line 25, in run
    secrets = get_file_secrets(constant.hives['system'], constant.hives['security'], is_vista_or_higher)
  File "C:\lago\Windows\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 183, in get_file_secrets
    return get_secrets(sysaddr, secaddr, vista)
  File "C:\lago\Windows\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 162, in get_secrets
    enc_secret = secaddr.read(enc_secret_value.Data.value, enc_secret_value.DataLength.value)
  File "C:\lago\Windows\lazagne\softwares\windows\creddump7\addrspace.py", line 110, in read
    for i in range(0, full_blocks):
TypeError: 'float' object cannot be interpreted as an integer

C:\Users\TESTACCOUNT\Desktop\Python37>

This is latest code.
I'm doing something wrong?

Thanks.

### PR DESCRIPTION
**Pull request by MyLoginOnGitHub**
Fix #459 
There could be another errors in reading blocks in HiveFileAddressSpace. Need to wait for reply from @Papotito123 in #459 to comfirm that this solved problem.

### CODE REVIEW

**Comment by MyLoginOnGitHub** [comment]
@Papotito123 replied, this PR solved the original problem

**Comment by byehack** [comment]
> @Papotito123 replied, this PR solved the original problem

use `//` is better instead `int`. `//` in python2 means `/`

**Comment by MyLoginOnGitHub** [comment]
> use // is better instead int.
Thanks! I will take this into account

**Comment by AlessandroZ** [comment]
Thanks :+1: 

I don't understand why is preferred // instead of int ?

**Comment by MyLoginOnGitHub** [comment]
When i googl'ed queries like "py2to3 division", all requests suggested to use //. No of them suggested to use int. I do not know why, but I believe them all -:)

**Comment by AlessandroZ** [comment]
For me the only different, it's the return type. On python 2, using // the return value will be truncated but still be a float: 
```
>>> 6.5//2
3.0
```
Whereas using int, it will returned an int
```
>>> int(6.5)/2
3
```
So both are correct, except if some functions accept only a particular type.

**Comment by MyLoginOnGitHub** [comment]
I really do not know. I just consider // as template for compatible with python2 and 3. Why // is prefferred?? Because another people do // :-).
And I suggest also do assert like https://github.com/MyLoginOnGitHub/LaZagne/blob/7f62bc15e3a7de701266592631be3b570669d100/Windows/lazagne/config/DPAPI/vault.py#L204. I think, it would be more clearly.

**Pull request merged**
