### PR TITLE
Try to extract passwords from all user contexts (Linux)

### PR DESCRIPTION
**Pull request by alxchk**
https://github.com/AlessandroZ/LaZagne/issues/121

I don't have all those software to check that something wasn't broken, but looks like most works ok. To feel the difference try to run as root on PC with running user sessions

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Awesome work !!! Thanks a lot.

**Comment by AlessandroZ** [comment]
I have added a missing tab to retrieve all profiles on firefox ([here](https://github.com/AlessandroZ/LaZagne/commit/57fc886a8bc743a97a92ba3936bc49e87e00ea96)).

And I have an error running the wallet module with sudo: 
```
sudo python laZagne.py wallet -g

raceback (most recent call last):
  File "laZagne.py", line 146, in launch_module
    pwdFound = module[i].run(i.capitalize())	# run the module
  File "/home/me/Linux/lazagne/softwares/wallet/libsecret.py", line 22, in run
    for session in homes.sessions():
  File "/home/me/Linux/lazagne/config/homes.py", line 79, in sessions
    previous = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```
The problem is that DBUS_SESSION_BUS_ADDRESS is in [environ](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/config/homes.py#L66) but not in [os.environ](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/config/homes.py#L79). 

So if replace every os.environ by environ or the contrary, it works without errors but not passwords were found. I don't know if you managed to retrieved passwords from wallets when sudo. 

Thanks again for your work.

**Comment by alxchk** [comment]
To be able to access dbus seteuid to the user should be done. I'll check what is wrong with sudo

**Comment by alxchk** [comment]
https://github.com/alxchk/LaZagne/commit/26c1bbaa540fa90af2b78fc1a412715ae1441bc0

I have no issues with sudo. Check that you have secretstorage installed for root user

**Comment by AlessandroZ** [comment]
I don't understand how it could work with sudo for wallets (at least on gnome and kde) because I had added a verification line to not run the tool with sudo ([gnome](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/gnome.py#L12) and [kde](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/kde.py#L17)).

For libsecrets, I have this error which is produced [here](https://github.com/AlessandroZ/LaZagne/blob/master/Linux/lazagne/softwares/wallet/libsecret.py#L30) (the error is catched by the except line so it's not a blocking point but no passwords are retrieved from this module). 
```
The '/org/freedesktop/secrets/aliases/default' object does not exist
The '/org/freedesktop/secrets/aliases/default' object does not exist
The '/org/freedesktop/secrets/aliases/default' object does not exist
The '/org/freedesktop/secrets/aliases/default' object does not exist
```

**Comment by alxchk** [comment]
Well, I don't know how gnome/kde works (don't use DEs for years), and didn't add enumeration for these modules. So enumeration (should) work just for libsecrets.
For libsecrets it tries to connect to user's session bus. So if you can retrieve passwords from user context and can't from root, then there may be several cases which may be debugged.
1. homes.sessions couldn't find proper dbus address.
2. for some strange reason dbus denies requests from the process.
3. for some strange reason libsecrets can't retrieve passwords from valid context.
You can try to check with strace where you connect when extraction is successful and compare to addresses which extracted by homes.session. Messages about 'object does not exist' comes from valid dbus session daemons which are not connected to desktop session with secrets provider.
What distribution do you use?

**Comment by AlessandroZ** [comment]
Ok I will investigate it on these possible errors when I will have some time.  

Here is my distribution: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

**Comment by alxchk** [comment]
I can reproduce but it's a bit non-trivial case. Will look into it deeper once have some time

**Comment by alxchk** [comment]
Well, situation is a bit sad. The situation is sad because dbus is shit and was written by shit masters. Looks like user session initialized only _once_ after library load.

**Comment by alxchk** [comment]
Please try my latest head - https://github.com/alxchk/LaZagne/commit/d4998058e671871c5e81ce2f35cbc9d686ba6e56

**Comment by AlessandroZ** [comment]
Ahaha you make me laugh, I could feel disappointment :)
> The situation is sad because dbus is shit and was written by shit masters.

With your new patch, it works great. It takes a little longer to execute but it works so it's great. Thanks a lot for your contribution. 
`elapsed time = 22.0574820042`

**Comment by AlessandroZ** [comment]
Just to let you now, it takes a bit longer because it receives a timeout response (but then I got all credentials). 
Here is the output written on the stdout: 
```
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by alxchk** [comment]
I started PR with omitting DBUS connections where secrets are not activated yet. This will be faster, but in theory there is probability that something may be missing (I think it's very unlikely, but maybe that can be checked)

**Pull request merged**
