### PR TITLE
Do not use modules with broken depensences

### PR DESCRIPTION
**Pull request by MyLoginOnGitHub**
Use dynamic import for Windows like in #560.  
I have tested the code, all works correctly. But I have no pyinstaller on windows. **Please**, test if pyinstaller works fine before merge.  
If you have no pyinstaller fow Windows too, tell me and I will install it to check.  
By the way, I have no MAC at all. I could to do the same thing for MAC, but I could not test it anywhere

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Hi @MyLoginOnGitHub, sorry for my late answer. I have no windows and Mac right now. I will install a new VM soon. If you could check it with pyinstaller it will be great, otherwise I could merge it and then I will test it. 

For Mac, if you could create a PR even if you didn't test it and I will do my best to test it. 

Thanks a lot. Have a nice day.

**Comment by MyLoginOnGitHub** [comment]
Ok, I'll try to do something useful this weekend

**Comment by MyLoginOnGitHub** [comment]
I've tested it. There was a bug, now it compilled successfully.

**Comment by AlessandroZ** [comment]
Awesome, thanks a lot ! :+1:

**Pull request merged**
