### PR TITLE
Support Python3

### PR DESCRIPTION
**Pull request by byehack**
except Windows/lazagne/softwares/windows/vault.py line51 other edits works fine in py2.

with vault.py line51 the app will be crashed in that line in py3 and this is a bug!

### CODE REVIEW

**Comment by AlessandroZ** [comment]
I have some problem with your PR that why I should take time to debug it to find the problem. I don't want to set the password to none to avoid a problem: https://github.com/AlessandroZ/LaZagne/pull/434/commits/2f1a6922cbc2a579fcf2570814ff05e94beb5a88#diff-53da2b1afac6dfc7525b0ffb5d72ef72R51

I appreciate your help. Let me some time to give it a look.

**Comment by byehack** [comment]
> I have some problem with your PR that why I should take time to debug it to find the problem. I don't want to set the password to none to avoid a problem: [2f1a692#diff-53da2b1afac6dfc7525b0ffb5d72ef72R51](https://github.com/AlessandroZ/LaZagne/commit/2f1a6922cbc2a579fcf2570814ff05e94beb5a88#diff-53da2b1afac6dfc7525b0ffb5d72ef72R51)
> 
> I appreciate your help. Let me some time to give it a look.

don't update this line. but for working on py3 others are important and must edit.

**Comment by byehack** [comment]
> I appreciate your help. Let me some time to give it a look.

just look at "vault.py line51" the program will end without any exit like "os._exit()".

**Comment by byehack** [comment]
i will other bugs and i will send a new PR to you....

**Pull request closed without merging**
