### PR TITLE
Fix UC Browser user impersonation, encoding error again 😅

### PR DESCRIPTION
**Pull request by ingested**
Fix encoding error when computer name (hostname) contains non-ascii chars

Also want to know your opinion about making the project pep8-compliant? I see you like tabs but this is not very pythonic.

- Replace tabs with 4 spaces
- Use `CamelCase` for classes only
- Use `ALL_UPPER_CASE` for global constants
- Use `snake_case` for everything else

### CODE REVIEW

**Comment by AlessandroZ** [comment]
I have no problem to make the projet pep8-compliant. If you want to replace all tabs with 4 spaces in all files, you can without problem (I will change my editor config to respect that) and for name convention, I totally agree. 

This only thing I want to keep even if it's not very pep8 compliant is the indent alignment between variables. I used to do that in C and I thing the code is more clear and human readable :). 
For example, if you have 2 variables with two different size name, you will add space to keep the aligment like this: 
```
alice = 'test'
bob   = 'test2'
```
But no problem to be pep8 compliant 👍

**Comment by AlessandroZ** [comment]
And another thing, I like is when printing using format with a name like this: 
`print '{name} does not exist'.format(name=path)`

I think it's more clear than: 
`print '{} does not exist'.format(path)`

**Comment by ingested** [comment]
Okay, cool, will do that when I have more time

**Comment by AlessandroZ** [comment]
I pushed some commits that I did some time ago to avoid conflict if you changed tabs to space or other things. So please, do not forget to be up to date before changing code. Thank you :)

**Pull request merged**
