### PR TITLE
Decode string

### LINKED ISSUE #326: laZagne 2.4 Dont run on windows
Hi. I don't know why i cant run laZagne.exe. I have this in my cmd:
Traceback (most recent call last):
  File "laZagne.py", line 234, in <module>
  File "laZagne.py", line 87, in runLaZagne
  File "lazagne\config\run.py", line 197, in run_lazagne
  File "lazagne\config\users.py", line 57, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
[3848] Failed to execute script laZagne 
HOW I can fix it. I'm not pro in this sfere.
If i run cmd as administrator i have the same problem please HELP MEEEEEEEEEEEEEEEEE))

### PR DESCRIPTION
**Pull request by plonibarploni**
This fixes #326

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Awesome, thanks. I have introduced this error when I wanted to migrate to python 3. I have removed sys.getfilesystemencoding() because it cannot be used on python 3. 

Thanks for your fix :+1:

**Comment by plonibarploni** [comment]
@AlessandroZ I don't think this should have been merged yet (to close #326), as the OP there didn't confirm that it worked for him. I also prepared an alternative [patch](https://github.com/plonibarploni/LaZagne/commit/cefaf4b13a5e9665031d85def180a63d5a130cd0) which can also be used with python3.

**Comment by AlessandroZ** [comment]
I don't understand what you meant, your fix has been merged on [master](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/users.py#L55) and @torerobo confirmed that it fixed the issue. I can reopen the issue but I think it has already been fixed.

**Comment by plonibarploni** [comment]
Yes, but the issue was originally opened by @Sladkiyperec and we haven't heard back from him whether it worked.

**Pull request merged**
