### PR TITLE
Central Cert Provider - IIS Server

### PR DESCRIPTION
**Pull request by aldorm**
This is a module to get passwords stored when Central Cert Provider is used in IIS Server.

It could store a Shared Resource, a Username, a Password and a Private Key Password (for Certs)

In the next URL you can get an idea of what Central Cert Provider is, and how to enabled it.
https://blogs.msdn.microsoft.com/kaushal/2012/10/11/central-certificate-store-ccs-with-iis-8-windows-server-2012/

Thanks!!

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Thank you very much for your PR. 
Before to merge it, I have a problem with some dependencies you used. I have spend lot of a time removing Crypto lib and I'm not a big fan adding it another time. I would prefer adding pure python code like [this one](https://github.com/bdauvergne/python-pkcs1/tree/master/pkcs1) or another project even if it's a bit slower. 
Do you mind, trying using pure python code. 

I had the same discussion with some other modules: https://github.com/AlessandroZ/LaZagne/issues/236

I hope you could do it, I would love to add your module to lazagne.

**Comment by aldorm** [comment]
Hi!!

I understand why you prefer pure-python code.

I was searching for a RSA pure-python implementation to adapt to the source code, what do you think about Stuvel project??  https://stuvel.eu/rsa

I supposed that is possible integrate those classes and methods to the module

What do you think ??

**Comment by AlessandroZ** [comment]
It seems great ;)

**Comment by AlessandroZ** [comment]
Well done, thanks a lot :+1:

**Pull request merged**
