### PR TITLE
Issue #187

### PR DESCRIPTION
**Pull request by csmali**
These files allows to install some of dependencies. For example "python-dbus" should be installed with apt-get for some debian based OS (Ubuntu in my case), so I changed wiki accordingly.

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Thanks !

**Comment by killercoderz4** [comment]
God day please can you assist with persistence. I am using lazagne in puppy via power shell one liner

**Comment by AlessandroZ** [comment]
`run persistence -h `

Please read the documentation or try to find by yourself. You cannot spam me on every threat. Thanks

**Comment by killercoderz4** [comment]
Apologies, never my intention to spam. Am new to puppy. I got a lot of stuff fixed and working. I just post to see if anyone had experienced similar issues. Of course I have read the documentation thoroughly, I fixed many issues  myself up to this point. I keep trying but I would appreciate any tips  I know it unrelated topic. Once again I sincerely apologise. For the multi post

**Pull request merged**
